version: '2'
services:

  jeeflow:
    image: shawoo/jeeflow:spi
    build: .
    restart: always
    command: ["uv", "run", "main_pg.py"]
    #command: ["uv", "run", "main.py"]
    ports:
      - "8101:8101"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8101/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - SPI_FOLDER=dev
      - FLOWS=false
      - SEEDS=false
      # - JEEFLOW_PG_DSN=postgresql://uid:pwd@127.0.0.1:5432/jeeflow
